- Gemfile
- Gemfile.lock
- app/mailers/booking_mailer.rb
- app/views/booking_mailer/booking_confirmed.html.erb
- app/views/booking_mailer/booking_saved.html.erb
- app/views/pages/home.html.erb
- config/environments/development.rb
- config/routes.rb
- db/seeds.rb
- test/mailers/booking_mailer_test.rb
- test/mailers/previews/booking_mailer_preview.rb
- BookingMailer creation
- booking_saved & booking_confirmed methods + mail templates created
- LetterOpener gem added (with config) to preview email sent directly in browser
- Templates linked to development homepage
Next on Mailer :
- AdminMailer (Devise gem required)
- Triggering mails in Model booking.rb (**to-do now**)
> BookingMailer setup with Save & Confirmation templates + development testing

- app/models/booking.rb
- Model booking : implementation of callback methods for booking mailings (saved, confirmed, updated, cancelled
- Model booking : implementation of callback methods for booking mailings (saved, confirmed, updated, cancelled
> Model booking : implementation of callback methods for booking mailings (saved, confirmed, updated, cancelled)

- Gemfile
- Gemfile.lock
- app/models/user.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/routes.rb
- db/migrate/20230118151539_devise_create_users.rb
- db/schema.rb
- test/fixtures/users.yml
- test/models/user_test.rb
I have hide the sign up form but maybe i can search a better and safer option later
> Add devise to the app and mask sign up (just let the log in)

- app/assets/config/manifest.js
- app/assets/stylesheets/application.scss
- app/javascript/application.js
- app/javascript/plugins/flatpickr.js
- app/views/bookings/new.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_form.html.erb
- config/tailwind.config.js
- db/migrate/20230124152522_rename_type_to_meal.rb
- package-lock.json
- package.json
- yarn.lock
Fix migration
Add style to form with tailwind on booking new
Add stimulus 
Add flatpickr
Add flatpickr to date in booking new
> Add front to new booking + flatpickr

- app/views/menus/edit.html.erb
- app/views/menus/index.html.erb
- app/views/menus/new.html.erb
- app/views/pages/restaurant.html.erb
Base of the front for Restaurant view & menu front rearrange.
- Div structure 
- tags(balises) structure
- exemple of images (unsplash)
> Restaurant v1

- db/migrate/20230124152522_rename_type_to_meal.rb
- db/migrate/20230202105711_remove_columns_to_menus.rb
- db/migrate/20230202110022_add_title_to_menus.rb
- db/migrate/20230202110146_add_price_to_menus.rb
- db/schema.rb
Debugging Menu DB : 
1. Put back the migration type to meal 
2. remove price and title 
3. And create 2 migrations to add again Title and Price
I think it's ok now check if it works on your side :)
> Menu db fixed

- app/views/bookings/index.html.erb
- app/views/shared/_form.html.erb
General style with table
Add different status style
Can add manually a new booking
Can view a booking
> Add general style + tab to index bookings

- app/controllers/meals_controller.rb
- app/models/meal.rb
- app/views/meals/edit.html.erb
- app/views/meals/index.html.erb
- app/views/meals/new.html.erb
- config/routes.rb
- db/migrate/20230202105711_remove_columns_to_menus.rb
- db/migrate/20230202110022_add_title_to_menus.rb
- db/migrate/20230202110146_add_price_to_menus.rb
- db/seeds.rb
Like the title describe. 
And we need to delete the 3 migration between "remane_type to meal" and "dropMenu" : 
1. remove colums to menus
2. add title to menus
3. add price to menus
> Renaming Menu to meal & delete migration rename<drop for debugging

- app/views/pages/restaurant.html.erb
- app/views/shared/_navbar.html.erb
1. NavBar prob with the other pages & opacity black - fixed but no more erb un NavBar with transparency in Home page
2. First Front Restaurant - dispatching and a little Front Tailwind mixed with CSS...
3. Image grouping fixed with CSS (last container) in Restaurant
> Restaurant front v1

- app/controllers/meals_controller.rb
- app/views/meals/index.html.erb
- app/views/shared/_navbar.html.erb
Changes on :  
- the view of index-Meals (Menu),
- Devise on Meals ... prob, so i skip_before_action :authenticate_user! 
- And the Nav Bar
> Meal front v3

- app/assets/stylesheets/components/_background-color.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_text-color.scss
- app/assets/stylesheets/config/_colors.scss
- app/controllers/pages_controller.rb
- app/views/pages/home.html.erb
- app/views/pages/home/_banner.html.erb
- app/views/pages/home/_video_section.html.erb
- app/views/pages/privatisation.html.erb
- app/views/pages/restaurant.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
-Front Home : cards, colors and others details
-NaBar & Footer : color and add privatisation (rename cuisine)
-Add files stylesheet scss : for the client colors and bg need like tailwind 
-Others little details to check (routes, etc)
> Home&meal front v4

- app/views/meals/index.html.erb
- app/views/pages/restaurant.html.erb
- Update the color "pink-pastel & red-pastel" (#B97456 & #9C5741) cf figma. 
- Last card restaurant done. 
- And others details
> Color client fixed & last cards restaurant fixed

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/config/_colors.scss
- app/controllers/bookings_controller.rb
- app/controllers/meals_controller.rb
- app/controllers/pages_controller.rb
- app/views/bookings/show.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/pages/admin.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_form.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- db/seeds.rb
**New Features :** 
- Added admin_path (/admin), through PagesController
- Admin board includes at the moment : 
- A table of all bookings (run **rails db:seed** to get bookings)
- Button to accept booking (decline function yet to come)
- Global button to log out as admin
- admin_path links have been added : 
- to the navbar when logged in
- to the footer globally (to remove depending on client's need)
**Next features :** 
- 'decline' booking button in Admin Table rows
- Sortable admin table with filter
- More visual, friendly table style
> Admin Board - Creation + Basics

- app/views/meals/index.html.erb
Add nil? method to Menu page for the access admin :
> Add nil? method to admin pass to Menu page

- app/javascript/application.js
- app/javascript/controllers/admin_controller.js
- app/javascript/controllers/hello_controller.js
- app/javascript/controllers/index.js
- app/views/pages/admin.html.erb
- app/views/shared/_bookings-table.html.erb
- admin tabs - in progress
- admin tabs - done & working with stimulus.js, yet to be filled with content, style and icons
- Bookings table cleaned
> admin bookings table

- .vscode/settings.json
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_admin.scss
- app/controllers/bookings_controller.rb
- app/controllers/concerns/filterable.rb
- app/helpers/bookings_helper.rb
- app/javascript/controllers/bookings_search_form_controller.js
- app/javascript/controllers/index.js
- app/models/booking.rb
- app/views/bookings/_bookings-table.html.erb
- app/views/pages/admin.html.erb
- config/routes.rb
- yarn.lock
- Bookings table sorting by column = done & tested
- Bookings table real-time search by last name w/ Stimulus
- Bookings table real-time search by last name w/ Stimulus
- Bookings table -> Search + Filtering by name simultaneously // with Filterable module implemented in Booking model
- Bookings table -> Searching by date of booking with Filterable + Flatpickr // Next -> Front, More search options, Reset button(s)
For more on these features : 
https://www.colby.so/posts/sortable-table-with-rails-and-turbo-frames
https://www.colby.so/posts/filtering-tables-with-rails-and-hotwire
> Admin bookings list table -> Made searchable & filterable at the same time (by name and date)

- app/views/bookings/_bookings-table.html.erb
- app/views/pages/admin.html.erb
- app/views/shared/_navbar.html.erb
- Fixing various display parameters & classes around Bookings Table in admin_path
- Fixing search fields position + Table width + Action buttons updated with emojis + Gray rows for past dates
> bookings table responsiveness

- app/assets/stylesheets/components/_background-color.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_menu.scss
- app/assets/stylesheets/components/_text-color.scss
- app/javascript/controllers/index.js
- app/javascript/controllers/navtabs_controller.js
- app/views/meals/index.html.erb
- config/tailwind.config.js
-Create Tab Menu : "Déjeuner" & "Diner" - Stimulus
-Add Color of the client in Tailwind 
-Test responsiveness Menu ... not ok ...
> Menu  responsive page create tab v2

- app/javascript/controllers/index.js
- app/javascript/controllers/navbar_controller.js
- app/views/shared/_navbar.html.erb
- Expandable menu on click. Still struggling with tailwind transitions
- Responsive navbar menu, toggled by a burger icon on mobile, with transition & stimulus management
> navbar responsive menu

- app/views/meals/index.html.erb
- app/views/pages/home.html.erb
- app/views/pages/home/_banner.html.erb
- app/views/pages/home/_video_section.html.erb
- db/migrate/20230310162112_add_timing_to_meals.rb
- db/schema.rb
- db/seeds.rb
- Add Wording Home & Menu
- change for Lunch and Dinner (migration)
> Wording menu+home

- app/controllers/meals_controller.rb
- app/views/meals/edit.html.erb
- app/views/meals/new.html.erb
- app/views/pages/_contact-privatisation.html.erb
- app/views/pages/privatisation.html.erb
JUST some simple form fixed : Front and back
> Views Meal form fixed

- app/views/layouts/application.html.erb
We can use Tailwind elements now with the CDN config. 
You can go to the website : 
[https://tailwind-elements.com/docs/standard/]
> Add tw elements to the project -Animation & others

- app/views/pages/home.html.erb
- app/views/pages/home/_carousel-article.html.erb
1. Add Carousel tw-element for Article to Home page (last container)
2. Render content to optimize the home page
> Carousel Article + render

- app/models/booking.rb
- app/models/privatisation.rb
- Model + Controller + Routes + Privatisation form rebuilt with simple_form
- CRUD with form validated + DB fixed to comply with form
- CRUD with form validated + DB fixed to comply with form
- Upgrading model validations before upgrading the forms - Privatisation + Booking
> model validations

- Gemfile.lock
- app/controllers/bookings_controller.rb
- app/controllers/meals_controller.rb
- app/controllers/newsletters_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/privatisations_controller.rb
- app/controllers/users/confirmations_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/controllers/users/passwords_controller.rb
- app/controllers/users/registrations_controller.rb
- app/controllers/users/sessions_controller.rb
- app/controllers/users/unlocks_controller.rb
- app/views/devise/sessions/new.html.erb
- app/views/layouts/private.html.erb
- app/views/pages/soon.html.erb
- config/routes.rb
- Opening Soon page created + Set as root_path + Authentication scope restricted for all controllers
- Sign in form cleaned up with corresponding layout
> Opening Soon page, with full authentication scope // Ready for pre-production

- app/views/meals/_lunch.html.erb
- app/views/meals/index.html.erb
- app/views/pages/home.html.erb
- app/views/pages/home/_cuisine-card.html.erb
- app/views/pages/home/_list-img.html.erb
- app/views/pages/home/_menu-home.html.erb
- app/views/pages/home/_privatisation-card.html.erb
- app/views/pages/home/_video_section.html.erb
- config/tailwind.config.js
- Upgraded Front and variable to Menu.
- Home : Animations & upgraded front (new variables of animation 'top' 'bot')
> Home -Animation & Front fixed + Menu- Front upgraded and Variable

- app/assets/stylesheets/config/_colors.scss
- app/views/pages/restaurant.html.erb
- app/views/pages/restaurant/_description-1.html.erb
- app/views/pages/restaurant/_description-2.html.erb
- app/views/pages/restaurant/_events.html.erb
- config/tailwind.config.js
Restaurant : 
- Animation : right & left
- Margin description 2 deleted for a better UI/UX (to improve in futur)
Colors : client request  
- File Tw config : colors specials changed 
- Same for Scss file colors
> Restaurant animation color

- app/views/privatisations/_carousel-privatisation.html.erb
- app/views/privatisations/new.html.erb
Just a little animation for the privat part
> Privatisation animation fixed

- app/views/layouts/application.html.erb
- app/views/layouts/private.html.erb
Bug with Tw element & Tailwindcss in the head and the compile. 
Tw element install with CDN because of install bug with yarn. 
Cleaning the head of Private file and, copy paste all the new CDN install in application.
> Bug fix - bug with Tw element & tailwindcss - CDN head

- app/views/layouts/application.html.erb
- config/environments/production.rb
Add config for Mailer production
Add favicon in the head application
> Mailer production v2

- app/views/layouts/application.html.erb
No relatif path, just the name file
> Favicon bug

- app/views/booking_mailer/booking_confirmed.html.erb
- app/views/booking_mailer/booking_modified.html.erb
- app/views/layouts/application.html.erb
- app/views/layouts/private.html.erb
- app/views/shared/_footer.html.erb
- Add favicon to private (soon)
- Add tel and content to mailer
- Add opening hours to footer and Insta link
> Mail content v2

- app/views/pages/soon.html.erb
Change for building web site in the soonPage
> Change text and infos soonPage

- app/views/bookings/new.html.erb
- app/views/meals/_dinner.html.erb
- app/views/meals/_lunch.html.erb
- app/views/meals/index.html.erb
- app/views/pages/home.html.erb
- app/views/pages/home/_banner.html.erb
- app/views/pages/home/_cuisine-card.html.erb
- app/views/pages/home/_list-img.html.erb
- app/views/pages/home/_menu-home.html.erb
- app/views/pages/home/_privatisation-card.html.erb
- app/views/pages/home/_video_section.html.erb
- app/views/pages/restaurant.html.erb
- app/views/pages/restaurant/_description-1.html.erb
- app/views/pages/restaurant/_description-4.html.erb
- app/views/pages/restaurant/_events.html.erb
- app/views/privatisations/new.html.erb
- app/views/shared/_footer.html.erb
Add images to all others pages
> Img home v2

- app/views/pages/home/_menu-home.html.erb
- app/views/pages/home/_privatisation-card.html.erb
- app/views/pages/home/_video_section.html.erb
- app/views/pages/restaurant/_description-1.html.erb
- app/views/pages/restaurant/_description-2.html.erb
- app/views/pages/restaurant/_description-4.html.erb
> Add modif text client & images

- app/views/meals/_dinner.html.erb
- app/views/meals/_lunch.html.erb
- app/views/pages/home/_privatisation-card.html.erb
- app/views/pages/restaurant/_events.html.erb
- app/views/privatisations/_carousel-privatisation.html.erb
- app/views/privatisations/new.html.erb
> Text client v4

- app/views/meals/_dinner.html.erb
- app/views/meals/_lunch.html.erb
- app/views/meals/index.html.erb
- app/views/pages/home/_cuisine-card.html.erb
- app/views/pages/home/_list-img.html.erb
- app/views/pages/home/_menu-home.html.erb
- app/views/pages/home/_privatisation-card.html.erb
- app/views/pages/home/_video_section.html.erb
- app/views/pages/restaurant.html.erb
- app/views/pages/restaurant/_description-2.html.erb
- app/views/pages/restaurant/_description-3.html.erb
- app/views/privatisations/new.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_navbar.html.erb
- config/application.rb
Optimize Text & html-front 
Hiding "language"
> Com marie modif

- app/controllers/bookings_controller.rb
- app/views/meals/_dinner.html.erb
- app/views/meals/_lunch.html.erb
- app/views/meals/index.html.erb
- app/views/pages/home/_cuisine-card.html.erb
- app/views/pages/home/_menu-home.html.erb
- app/views/pages/home/_video_section.html.erb
- app/views/pages/restaurant.html.erb
- app/views/pages/restaurant/_description-1.html.erb
- app/views/pages/restaurant/_description-3.html.erb
- app/views/pages/restaurant/_description-4.html.erb
- app/views/privatisations/_carousel-privatisation.html.erb
- app/views/privatisations/new.html.erb
Add text and changes 
Add test mailer admin notify when creating a booking
> Text marie v2

- app/controllers/meals_controller.rb
Bug fixed new meal in meal controller (missing timing)
> Meal controller add timing

- app/controllers/bookings_controller.rb
- app/controllers/meals_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/privatisations_controller.rb
- config/routes.rb
- Hiding the opening soon 
- Root changed
- Skip before action User - controllers : for the production
> Production done without translation

- app/views/meals/index.html.erb
Pdf Menu link "lunch and dinner" updated
> updated Menu Pdf end of June

- app/views/meals/index.html.erb
- app/views/pages/home/_banner.html.erb
- app/views/pages/home/_list-img.html.erb
- app/views/pages/home/_menu-home.html.erb
- app/views/privatisations/_carousel-privatisation.html.erb
- New lunch pdf in home page & meal page 
- Btn banner home page fixed
- img list home page changed & carousel privat
> Add new lunch & img restaurant & butns fixed"

- app/views/bookings/new.html.erb
Add the iFrame tag ZenChef to the booking new page.
And Stop the booking mode with Mailer and BookingController (sharedForm replaced).
> Add iFrame tag Zenchef
